apiVersion: v1
kind: Pod
metadata: 
  name: sample3
spec: 
  containers: 
    - name: debug
      image: centos:7
      command:
      - sleep
      - "10000"
      env:
        - name: URL
          #value: google.com
          valueFrom:
            configMapKeyRef:
              key: URl
              name: sample-meta


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-meta
data:
  URL: yahoo.com
  ENV: dev
  PROJECT: sample