apiVersion: v1
kind: Pod
metadata:
  name: sample7
spec:
  containers:
  - name: app
    image: centos:7
    - sleep 
    - "10000"
    resources:
      requests:
        memory: "64Mi"
        cpu: "25m"
      limits:
        memory: "128Mi"
        cpu: "50m"