apiVersion: v1
kind: Pod
metadata:
  name: sample6
spec:
  containers:
  - image: centos:7
    name: centos
    command:
    - sleep
    - "100000"
    resources:
      requests:
        memory: "64Mi"
        cpu: "25m"
      limits:
        memory: "128Mi"
        cpu: "50m"